server:
  servlet:
    context-path: /exo
spring:
  datasource:
    dbcp2:
      initial-size: 5
      max-total: 10
    driver-class-name: org.postgresql.Driver
    password: postgres
    url: jdbc:postgresql://localhost:5432/exo
    username: postgres
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        format_sql: true
        show_sql: true
 